const tarjetasCharla = [
    "¿Qué cosas te hacían sentir deseada cuando éramos más jóvenes? ¿Y hoy?",
    "¿Qué momento íntimo nuestro recordás como uno de los más especiales?",
    "¿Contémonos qué es lo que más nos atrae del otro hoy, después de tantos años juntos.",
    "Proponé una idea nueva para nuestra intimidad y yo propondré otra. Elijamos una para probar.",
    "¿Qué cosas te gustaría cambiar (aunque sea un poquito) de nuestra rutina sexual?",
    "Redefinamos la intimidad: ¿qué significa para cada uno ser verdaderamente íntimos a esta edad?",
    "Si pudieras contarme un deseo íntimo sin miedo a que te juzgue o te lo exija… ¿cuál sería?",
    "Hagamos una ronda de preguntas atrevidas. Uno pregunta, el otro responde sin filtro.",
    "Recordemos juntos nuestro primer beso. ¿Dónde fue? ¿Qué sentimos? ¿Qué vino después?",
    "¿Hay algo que siempre quisiste probar pero nunca te animaste a decirme?",
    "Imaginemos una noche ideal juntos… ¿qué incluiría desde que empieza hasta que termina?",
    "¿Hay alguna caricia, palabra o actitud que te encienda especialmente… pero que nunca me pediste?",
    "Si tuvieras que seducirme desde cero esta noche, ¿qué harías distinto?",
    "¿Qué parte de tu cuerpo te gustaría que explore más… y cómo?",
    "¿Te animás a contarme una fantasía que te excite, aunque no la queramos concretar?",
    "¿Recordás alguna vez que sentiste que me deseabas con solo mirarme? ¿Qué pasaba en ese momento?",
    "¿Qué te haría sentir más libre en nuestra intimidad?",
    "¿Hay algo que hacíamos antes y te gustaría que retomemos en nuestra vida sexual?",
    "¿Qué tipo de palabras o gestos te hacen sentir sexy, no solo querido/a?",
    "¿Qué lugar fuera de casa te parecería excitante para tener un encuentro íntimo?",
    "Si te pidiera que me sorprendas en nuestra próxima noche juntos… ¿por dónde empezarías?",
    "¿Qué escena de película o serie te quedó grabada como algo que te gustaría vivir?",
    "¿Preferís que la intimidad empiece con ternura o con tensión sexual… o una mezcla?",
    "Tarea para el próximo encuentro sexual: Cada uno elige una prenda sexy para que el otro se ponga... y después vemos qué pasa.",
    "Tarea para el próximo encuentro sexual: Escribamos (por separado) una carta de deseo: lo que más nos gustaría que el otro haga, sin filtros."
];

const tarjetasAccion = [
    "Dale una caricia como la que te gustaría recibir, sin decir nada, solo a través del tacto y mirando a los ojos.",
    "Dale un beso en una parte del cuerpo que normalmente no besás.",
    "Susurrale algo al oído que te gustaría hacerle esta noche.",
    "Explorá su cuerpo lentamente durante unos minutos, sin decir una palabra.",
    "Dale un masaje íntimo, tomándote tu tiempo.",
    "Proponé una fantasía breve y representala.",
    "Dale una orden sexy que él o ella deba cumplir.",
    "Besalo/a como si fuera la primera vez.",
    "Sacale una prenda lentamente, con contacto visual todo el tiempo.",
    "Hacelo/a gemir sin usar tus manos.",
    "Inventá un apodo sexy para esta noche y usalo sin parar.",
    "Usá solo tu boca y lengua durante unos minutos (¡con imaginación!).",
    "Jugá a que no podés hablar… pero sí seducir.",
    "Hacelo/a esperar… y desearte más antes de actuar.",
    "Improvisá un striptease divertido y sexy.",
    "Acaricialo/a solo por encima de la ropa interior… durante algunos minutos. Sin pasar el límite.",
    "Narrale al oído una fantasía que incluya a los dos… sin censura.",
    "Quitale la ropa con la boca (o intentalo).",
    "Jugá a que sos un desconocido/a en un encuentro prohibido. Actuá ese papel por 5 minutos.",
    "Proponé una postura sexual… y explicá por qué te calienta tanto.",
    "Hacé que se siente… y quedate encima sin moverte, solo respirando profundo, cara a cara.",
    "Describile en detalle lo que le harías si no hubiera reglas esta noche.",
    "Besale todo el cuerpo, excepto donde más lo desea.",
    "Atalo/a con una prenda tuya… y hacelo/a desearte antes de soltarlo/a.",
    "Pedile que te dé una orden, pero sorprendelo/a cumpliéndola a tu manera.",
    "Hacelo/a tocarse frente a vos, pero solo si lo mirás sin tocar.",
    "Llevá una parte de su cuerpo a tu boca… y no digas una palabra mientras lo hacés.",
    "Hacé una pausa en medio del juego… y pedile que te suplique seguir.",

    // Solo para ella:
    "Ella: Elegí la prenda más sexy que tengas, ponétela… y hacé como si no te dieras cuenta de cuánto me estás provocando.",
    "Ella: Vestite con lencería, medias o algo que te haga sentir deseada… y mostrame lo que elegiste como si fuera un secreto.",
    "Ella: Ponete solo una tanga y una camisa, acercate sin decir nada… y dejá que mi imaginación se encargue del resto.",
    "Ella: Usá un vestidito corto sin ropa interior… y hacé que se note.",
    "Ella: Elegí una prenda que nunca te animaste a usar… y usala solo para mí esta noche.",
    "Ella: Vestite con algo transparente o con aberturas… y mostrame cómo se ve desde todos los ángulos."
];