const tarjetasCharla = [
    "¿Qué cosas te hacían sentir deseada cuando éramos más jóvenes? ¿Y hoy?",
    "¿Qué momento íntimo nuestro recordás como uno de los más especiales?",
    "¿Contémonos qué es lo que más nos atrae del otro hoy, después de tantos años juntos.",
    "Proponé una idea nueva para nuestra intimidad y yo propondré otra. Elijamos una para probar.",
    "¿Qué cosas te gustaría cambiar (aunque sea un poquito) de nuestra rutina sexual?",
    "Redefinamos la intimidad: ¿qué significa para cada uno ser verdaderamente íntimos a esta edad?",
    "Si pudieras contarme un deseo íntimo sin miedo a que te juzgue o te lo exija… ¿cuál sería?",
    "Hagamos una ronda de preguntas atrevidas. Uno pregunta, el otro responde sin filtro.",
    "Recordemos juntos nuestro primer beso. ¿Dónde fue? ¿Qué sentimos? ¿Qué vino después?",
    "Tarea para el próximo encuentro sexual: Cada uno elige una prenda sexy para que el otro se ponga... y después vemos qué pasa.",
    "Tarea para el próximo encuentro sexual: Escribamos (por separado) una carta de deseo: lo que más nos gustaría que el otro haga, sin filtros."
];

const tarjetasAccion = [
    "Dale una caricia como la que te gustaría recibir, sin decir nada, solo a través del tacto y mirando a los ojos.",
    "Dale un beso en una parte del cuerpo que normalmente no besás.",
    "Susurrale algo al oído que te gustaría hacerle esta noche.",
    "Explorá su cuerpo lentamente durante unos minutos, sin decir una palabra.",
    "Dale un masaje íntimo, tomándote tu tiempo.",
    "Proponé una fantasía breve y representala.",
    "Dale una orden sexy que él o ella deba cumplir.",
    "Besalo/a como si fuera la primera vez.",
    "Sacale una prenda lentamente, con contacto visual todo el tiempo.",
    "Hacelo/a gemir sin usar tus manos.",
    "Inventá un apodo sexy para esta noche y usalo sin parar.",
    "Usá solo tu boca y lengua durante unos minutos (¡con imaginación!).",
    "Jugá a que no podés hablar… pero sí seducir.",
    "Hacelo/a esperar… y desearte más antes de actuar.",
    "Usá una prenda sexy para seducirlo/a en silencio.",
    "Improvisá un striptease divertido y sexy.",

    // Nuevas, más atrevidas:
    "Acaricialo/a solo por encima de la ropa interior… durante algunos minutos. Sin pasar el límite.",
    "Narrale al oído una fantasía que incluya a los dos… sin censura.",
    "Quitale la ropa con la boca (o intentalo).",
    "Jugá a que sos un desconocido/a en un encuentro prohibido. Actuá ese papel por 5 minutos.",
    "Proponé una postura sexual… y explicá por qué te calienta tanto.",
    "Hacé que se siente… y quedate encima sin moverte, solo respirando profundo, cara a cara.",
    "Describile en detalle lo que le harías si no hubiera reglas esta noche.",
    "Besale todo el cuerpo, excepto donde más lo desea.",
    "Atalo/a con una prenda tuya… y hacelo/a desearte antes de soltarlo/a.",
    "Pedile que te dé una orden, pero sorprendelo/a cumpliéndola a tu manera.",
    "Hacelo/a tocarse frente a vos, pero solo si lo mirás sin tocar.",
    "Llevá una parte de su cuerpo a tu boca… y no digas una palabra mientras lo hacés.",
    "Hacé una pausa en medio del juego… y pedile que te suplique seguir.",
    //Vestimenta sexy
    "Elegí la prenda más sexy que tengas, ponétela… y hacé como si no te dieras cuenta de cuánto me estás provocando.",
    "Vestite con lencería, medias o algo que te haga sentir deseada… y mostrame lo que elegiste como si fuera un secreto.",
    "Ponete solo una tanga y una camisa, acercate sin decir nada… y dejá que mi imaginación se encargue del resto.",
    "Usá un vestidito corto sin ropa interior… y hacé que se note.",
    "Elegí una prenda que nunca te animaste a usar… y usala solo para mí esta noche.",
    "Vestite con algo transparente o con aberturas… y mostrame cómo se ve desde todos los ángulos.",
];
